#!/bin/sh
GIT_WORK_TREE=/var/lib/jenkins/workspace/itrust_job1/production-www/ git checkout -f
cd /var/lib/jenkins/workspace/itrust_job1/iTrust/iTrustProvision && sudo ansible-playbook -i localhost newdroplet.yml

